// Top-level build.gradle file
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/groups/public/" }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://s01.oss.sonatype.org/content/groups/public/" }
    }
}
