import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";

dotenv.config();

console.log(`[SERVER START] NODE_ENV: ${process.env.NODE_ENV}`);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const supabaseUrl = process.env.SUPABASE_URL || "https://zkblysthqcmspaxiodur.supabase.co";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";

const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Supabase SQL Schema for Production:
 * 
 * -- 1. Create the users table
 * CREATE TABLE IF NOT EXISTS public.users (
 *   username TEXT PRIMARY KEY,
 *   password TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 2. Create the posts table
 * CREATE TABLE IF NOT EXISTS public.posts (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   username TEXT REFERENCES public.users(username) ON DELETE CASCADE,
 *   content TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 3. Disable Row Level Security (RLS)
 * ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
 * ALTER TABLE public.posts DISABLE ROW LEVEL SECURITY;
 * 
 * -- 4. Create the Sync Function
 * CREATE OR REPLACE FUNCTION public.handle_new_user() 
 * RETURNS trigger 
 * LANGUAGE plpgsql 
 * SECURITY DEFINER SET search_path = public
 * AS $$
 * BEGIN
 *   INSERT INTO public.users (username, password)
 *   VALUES (new.email, 'google_authenticated_user')
 *   ON CONFLICT (username) DO NOTHING;
 *   RETURN new;
 * END;
 * $$;
 * 
 * -- 5. Create the Trigger
 * DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
 * CREATE TRIGGER on_auth_user_created
 *   AFTER INSERT ON auth.users
 *   FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
 * 
 * -- 6. Backfill existing users
 * INSERT INTO public.users (username, password)
 * SELECT email, 'google_authenticated_user'
 * FROM auth.users
 * ON CONFLICT (username) DO NOTHING;
 */

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // GLOBAL LOG - Catch every single request
  app.use((req, res, next) => {
    console.log(`[SERVER LOG] ${new Date().toISOString()} - ${req.method} ${req.url}`);
    next();
  });

  // Health check
  app.get("/api/health", (req, res) => {
    console.log("Health check requested");
    res.json({ 
      status: "ok", 
      env: process.env.NODE_ENV,
      time: new Date().toISOString()
    });
  });

  // Auth Routes
  app.post("/api/register", async (req, res) => {
    const { username, password } = req.body;
    if (!username || !password) {
      return res.status(400).json({ error: "Username and password are required" });
    }
    
    console.log(`Attempting to register user: ${username}`);
    
    const { data, error } = await supabase
      .from('users')
      .insert([{ username, password }])
      .select();

    if (error) {
      console.error('Supabase Registration Error:', error);
      const isDuplicate = error.message?.includes('duplicate key') || error.code === '23505';
      return res.status(400).json({ 
        error: isDuplicate ? "Username already exists" : error.message 
      });
    }
    
    console.log(`User registered successfully: ${username}`);
    res.json({ success: true });
  });

  app.post("/api/login", async (req, res) => {
    const { username, password } = req.body;
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .eq('password', password)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        return res.status(401).json({ error: "Invalid username or password" });
      }
      console.error('Supabase Login Error:', error);
      return res.status(401).json({ error: error.message });
    }

    if (data) {
      res.json({ success: true, username: data.username });
    } else {
      res.status(401).json({ error: "Invalid username or password" });
    }
  });

  // API Routes
  app.get("/api/posts", async (req, res) => {
    const { data, error } = await supabase
      .from('posts')
      .select('*')
      .order('created_at', { ascending: false });
    
    if (error) return res.status(500).json({ error: error.message });
    res.json(data || []);
  });

  app.post("/api/posts", async (req, res) => {
    const { username, content } = req.body;
    if (!username || !content) {
      return res.status(400).json({ error: "Username and content are required" });
    }
    
    try {
      const { error: userError } = await supabase
        .from('users')
        .upsert([{ username, password: 'google_authenticated_user' }], { onConflict: 'username' });

      if (userError) console.error('Error ensuring user exists:', userError);

      const { data, error } = await supabase
        .from('posts')
        .insert([{ username, content }])
        .select()
        .single();

      if (error) {
        console.error('Supabase Post Error:', error);
        return res.status(500).json({ 
          error: error.message,
          details: error.details,
          hint: error.hint,
          code: error.code
        });
      }
      
      res.json(data);
    } catch (err: any) {
      console.error('Server Post Error:', err);
      res.status(500).json({ error: err.message || "Internal server error" });
    }
  });

  app.put("/api/posts/:id", async (req, res) => {
    const { id } = req.params;
    const { username, content } = req.body;

    if (!username || !content) {
      return res.status(400).json({ error: "Username and content are required" });
    }

    const { data, error } = await supabase
      .from('posts')
      .update({ content })
      .eq('id', id)
      .eq('username', username)
      .select()
      .single();

    if (error) {
      console.error('Supabase Update Error:', error);
      return res.status(500).json({ error: error.message });
    }

    res.json(data);
  });

  app.delete("/api/posts/:id", async (req, res) => {
    const { id } = req.params;
    const { username } = req.body;

    if (!username) {
      return res.status(400).json({ error: "Username is required" });
    }

    const { error } = await supabase
      .from('posts')
      .delete()
      .eq('id', id)
      .eq('username', username);

    if (error) {
      console.error('Supabase Delete Error:', error);
      return res.status(500).json({ error: error.message });
    }

    res.json({ success: true });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production static serving
    app.use(express.static(path.resolve(__dirname, "dist")));
    app.get("*", (req, res) => {
      res.sendFile(path.resolve(__dirname, "dist", "index.html"));
    });
  }

  // Final catch-all for debugging
  app.use((req, res) => {
    console.log(`[SERVER 404] ${req.method} ${req.url}`);
    if (req.url.startsWith('/api')) {
      res.status(404).json({ error: `API route not found: ${req.method} ${req.url}` });
    } else {
      res.status(404).send("Page not found");
    }
  });

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
    console.log(`Environment: ${process.env.NODE_ENV || 'development'}`);
  });

  // Global error handler
  app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
    console.error('Unhandled Server Error:', err);
    res.status(500).json({ error: "Internal Server Error", details: err.message });
  });
}

startServer();
