import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL || "https://zkblysthqcmspaxiodur.supabase.co";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";

const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Supabase SQL Schema for this app:
 * 
 * -- 1. Create the users table
 * CREATE TABLE IF NOT EXISTS users (
 *   username TEXT PRIMARY KEY,
 *   password TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 2. Create the posts table
 * CREATE TABLE IF NOT EXISTS posts (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   username TEXT REFERENCES users(username) ON DELETE CASCADE,
 *   content TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT NOW()
 * );
 * 
 * -- 3. IMPORTANT: Disable Row Level Security (RLS) 
 * -- This allows the app to read/write using the Anon key without complex policies.
 * -- This is the most common reason for "not posting" or "login failed" errors.
 * ALTER TABLE users DISABLE ROW LEVEL SECURITY;
 * ALTER TABLE posts DISABLE ROW LEVEL SECURITY;
 * 
 * -- 4. Insert the admin user
 * INSERT INTO users (username, password) 
 * VALUES ('Ashur@admin.com', '12345678')
 * ON CONFLICT (username) DO NOTHING;
 */

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Auth Routes
  app.post("/api/register", async (req, res) => {
    const { username, password } = req.body;
    if (!username || !password) {
      return res.status(400).json({ error: "Username and password are required" });
    }
    
    // In a real app, we'd use Supabase Auth, but for a simple "text post" app 
    // we'll just use a 'users' table to match the previous logic.
    const { data, error } = await supabase
      .from('users')
      .insert([{ username, password }])
      .select();

    if (error) {
      return res.status(400).json({ error: error.message === 'duplicate key value violates unique constraint "users_pkey"' ? "Username already exists" : error.message });
    }
    res.json({ success: true });
  });

  app.post("/api/login", async (req, res) => {
    const { username, password } = req.body;
    const { data, error } = await supabase
      .from('users')
      .select('*')
      .eq('username', username)
      .eq('password', password)
      .single();

    if (error) {
      // PGRST116 is the code for "no rows returned"
      if (error.code === 'PGRST116') {
        return res.status(401).json({ error: "Invalid username or password" });
      }
      console.error('Supabase Login Error:', error);
      return res.status(401).json({ error: error.message });
    }

    if (data) {
      res.json({ success: true, username: data.username });
    } else {
      res.status(401).json({ error: "Invalid username or password" });
    }
  });

  // API Routes
  app.get("/api/posts", async (req, res) => {
    const { data, error } = await supabase
      .from('posts')
      .select('*')
      .order('created_at', { ascending: false });
    
    if (error) return res.status(500).json({ error: error.message });
    res.json(data || []);
  });

  app.post("/api/posts", async (req, res) => {
    const { username, content } = req.body;
    if (!username || !content) {
      return res.status(400).json({ error: "Username and content are required" });
    }
    
    try {
      // Ensure user exists in our 'users' table (especially for Google Auth users)
      const { error: userError } = await supabase
        .from('users')
        .upsert([{ username, password: 'google_authenticated_user' }], { onConflict: 'username' });

      if (userError) {
        console.error('Error ensuring user exists:', userError);
        // We continue, but this might cause the post insert to fail if FK is active
      }

      const { data, error } = await supabase
        .from('posts')
        .insert([{ username, content }])
        .select()
        .single();

      if (error) {
        console.error('Supabase Post Error:', error);
        return res.status(500).json({ error: error.message });
      }
      
      res.json(data);
    } catch (err: any) {
      console.error('Server Post Error:', err);
      res.status(500).json({ error: err.message || "Internal server error" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production static serving
    app.use(express.static(path.resolve(__dirname, "dist")));
    app.get("*", (req, res) => {
      res.sendFile(path.resolve(__dirname, "dist", "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
